Proper AUFS support
This patch is what we have been using for the Pentoo LiveCDs for about 5
years with the changes suggested by lxnay merged in.  As much as
possible has been addressed (with the exception of the man page
documentation).  Please review this code as the next version will likely
be suggested for inclusion (once I write the documentation for the new
features).

Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>

diff --git a/defaults/linuxrc b/defaults/linuxrc
--- a/defaults/linuxrc
+++ b/defaults/linuxrc
@@ -253,6 +253,38 @@ do
 		aufs)
 			USE_AUFS_NORMAL=1
 		;;
+		aufs\=*)
+			USE_AUFS_NORMAL=1
+			CMD_AUFS=$(parse_opt "${x}")
+			echo ${CMD_AUFS}|grep , >/dev/null 2>&1
+			if [ "$?" -eq '0' ]
+			then
+				UID=$(echo ${CMD_AUFS#*,})
+				AUFS=$(echo ${CMD_AUFS%,*})
+			else
+				AUFS=${CMD_AUFS}
+			fi
+		;;
+		aufs.changes\=*)
+			USE_AUFS_NORMAL=1
+			CMD_AUFS=$(parse_opt "${x}")
+			echo ${CMD_AUFS}|grep , >/dev/null 2>&1
+			if [ "$?" -eq '0' ]
+			then
+				UID=$(echo ${CMD_AUFS#*,})
+				AUFS=$(echo ${CMD_AUFS%,*})
+			else
+				AUFS=${CMD_AUFS}
+			fi
+		;;
+		aufs.persistent)
+			USE_AUFS_NORMAL=1
+			AUFS="detect"
+		;;
+		# Allow user to specify the modules location
+		aufs.modules\=*)
+			MODULESD=$(parse_opt "${x}")
+		;;
 		unionfs)
 			if [ ! -x /sbin/unionfs ]
 			then
@@ -425,17 +457,24 @@ rundebugshell "before setting up the root filesystem"
 
 if [ "${CDROOT}" = '1' ]
 then
-	good_msg "Making tmpfs for ${NEW_ROOT}"
-	mount -n -t tmpfs tmpfs "${NEW_ROOT}"
+	setup_aufs
+	if [ "${USE_AUFS_NORMAL}" -eq '1' ]
+	then
+		CHROOT=${UNION}
+	else
+		CHROOT=${NEW_ROOT}
+		good_msg "Making tmpfs for ${NEW_ROOT}"
+		mount -n -t tmpfs tmpfs ${NEW_ROOT}
 
-	for i in dev mnt proc run sys tmp mnt/livecd mnt/key tmp/.initrd mnt/gentoo
-	do
-		mkdir -p "${NEW_ROOT}/${i}"
-		chmod 755 "${NEW_ROOT}/${i}"
-	done
-	[ ! -d "${CDROOT_PATH}" ] && mkdir -p "${CDROOT_PATH}"
-	[ ! -e "${NEW_ROOT}/dev/null" ] && mknod "${NEW_ROOT}"/dev/null c 1 3
-	[ ! -e "${NEW_ROOT}/dev/console" ] && mknod "${NEW_ROOT}"/dev/console c 5 1
+		for i in dev mnt ${CDROOT_PATH} mnt/livecd mnt/key tmp tmp/.initrd mnt/gentoo sys
+		do
+			mkdir -p "${NEW_ROOT}/${i}"
+			chmod 755 "${NEW_ROOT}/${i}"
+		done
+		[ ! -d "${CDROOT_PATH}" ] && mkdir -p "${CDROOT_PATH}"
+		[ ! -e "${NEW_ROOT}/dev/null" ] && mknod "${NEW_ROOT}"/dev/null c 1 3
+		[ ! -e "${NEW_ROOT}/dev/console" ] && mknod "${NEW_ROOT}"/dev/console c 5 1
+	fi
 
 	# For SGI LiveCDs ...
 	if [ "${LOOPTYPE}" = "sgimips" ]
@@ -451,7 +490,7 @@ then
 		[ ! -e "${NEW_ROOT}/dev/tty1" ] && mknod "${NEW_ROOT}/dev/tty1" c 4 1
 	fi
 
-	if [ "${REAL_ROOT}" != "/dev/nfs" ] && [ "${LOOPTYPE}" != "sgimips" ]
+	if [ "${REAL_ROOT}" != "/dev/nfs" ] && [ "${LOOPTYPE}" != "sgimips" ] && [ "${USE_AUFS_NORMAL}" != '1' ]
 	then
 		bootstrapCD
 	fi
@@ -763,7 +802,23 @@ then
 		fi
 	fi
 
+	if [ "${USE_AUFS_NORMAL}" -eq '1' ]
+	then
+		union_insert_dir ${UNION} ${NEW_ROOT}/${FS_LOCATION}
 
+		# Make sure fstab notes livecd is mounted ro.  Makes system skip remount which fails on aufs dirs.
+		sed -e 's|\(.*\s/\s*tmpfs\s*\)defaults\(.*\)|\1defaults,ro\2|' /${UNION}/etc/fstab > /${UNION}/etc/fstab.new
+		mv /${UNION}/etc/fstab.new /${UNION}/etc/fstab
+		warn_msg "Adding all modules in $MODULESD/modules/"
+		if [ -z "${MODULESD}" ]
+		then
+			union_insert_modules ${CDROOT_PATH}
+		else
+			mkdir ${NEW_ROOT}/mnt/modulesd
+			mount "${MODULESD}" ${NEW_ROOT}/mnt/modulesd
+			union_insert_modules ${NEW_ROOT}/mnt/modulesd
+		fi
+	fi
 
 	# Unpacking additional packages from NFS mount
 	# This is useful for adding kernel modules to /lib
@@ -786,56 +841,60 @@ then
 	then
 		setup_unionfs ${NEW_ROOT} /${FS_LOCATION}
 		CHROOT=/union
-	elif [ "${USE_AUFS_NORMAL}" != '1' ]; then
-
-	good_msg "Copying read-write image contents to tmpfs"
-	# Copy over stuff that should be writable
-	(cd "${NEW_ROOT}/${FS_LOCATION}"; cp -a ${ROOT_TREES} "${NEW_ROOT}") || {
-		bad_msg "Copying failed, dropping into a shell."
-		do_rundebugshell
-	}
-
-	# Now we do the links.
-	for x in ${ROOT_LINKS}
-	do
-		if [ -L "${NEW_ROOT}/${FS_LOCATION}/${x}" ]
+	else
+	#XXX Note to potential reviewers. diff formats this section very very oddly. Be sure to review this hunk after applied, do NOT simply read the diff
+		if [ ! "${USE_AUFS_NORMAL}" -eq '1' ]
 		then
-			ln -s "$(readlink ${NEW_ROOT}/${FS_LOCATION}/${x})" "${x}" 2>/dev/null
-		else
-			# List all subdirectories of x
-			find "${NEW_ROOT}/${FS_LOCATION}/${x}" -type d 2>/dev/null | while read directory
-			do
-				# Strip the prefix of the FS_LOCATION
-				directory="${directory#${NEW_ROOT}/${FS_LOCATION}/}"
+			good_msg "Copying read-write image contents to tmpfs"
+			# Copy over stuff that should be writable
+			(cd "${NEW_ROOT}/${FS_LOCATION}"; cp -a ${ROOT_TREES} "${NEW_ROOT}") || {
+				bad_msg "Copying failed, dropping into a shell."
+				do_rundebugshell
+			}
 
-				# Skip this directory if we already linked a parent directory
-				if [ "${current_parent}" != '' ]; then
-					var=$(echo "${directory}" | grep "^${current_parent}")
-					if [ "${var}" != '' ]; then
-						continue
-					fi
-				fi
-				# Test if the directory exists already
-				if [ -e "/${NEW_ROOT}/${directory}" ]
+			# Now we do the links.
+			for x in ${ROOT_LINKS}
+			do
+				if [ -L "${NEW_ROOT}/${FS_LOCATION}/${x}" ]
 				then
-					# It does exist, link all the individual files
-					for file in $(ls /${NEW_ROOT}/${FS_LOCATION}/${directory})
+					ln -s "$(readlink ${NEW_ROOT}/${FS_LOCATION}/${x})" "${x}" 2>/dev/null
+				else
+					# List all subdirectories of x
+					find "${NEW_ROOT}/${FS_LOCATION}/${x}" -type d 2>/dev/null | while read directory
 					do
-					if [ ! -d "/${NEW_ROOT}/${FS_LOCATION}/${directory}/${file}" ] && [ ! -e "${NEW_ROOT}/${directory}/${file}" ]; then
-							ln -s "/${FS_LOCATION}/${directory}/${file}" "${directory}/${file}" 2> /dev/null
+						# Strip the prefix of the FS_LOCATION
+						directory="${directory#${NEW_ROOT}/${FS_LOCATION}/}"
+
+						# Skip this directory if we already linked a parent directory
+						if [ "${current_parent}" != '' ]; then
+							var=$(echo "${directory}" | grep "^${current_parent}")
+							if [ "${var}" != '' ]; then
+								continue
+							fi
+						fi
+						# Test if the directory exists already
+						if [ -e "/${NEW_ROOT}/${directory}" ]
+						then
+							# It does exist, link all the individual files
+							for file in $(ls /${NEW_ROOT}/${FS_LOCATION}/${directory})
+							do
+								if [ ! -d "/${NEW_ROOT}/${FS_LOCATION}/${directory}/${file}" ] && [ ! -e "${NEW_ROOT}/${directory}/${file}" ]; then
+									ln -s "/${FS_LOCATION}/${directory}/${file}" "${directory}/${file}" 2> /dev/null
+								fi
+							done
+						else
+							# It does not exist, make a link to the livecd
+							ln -s "/${FS_LOCATION}/${directory}" "${directory}" 2>/dev/null
+							current_parent="${directory}"
 						fi
 					done
-				else
-					# It does not exist, make a link to the livecd
-					ln -s "/${FS_LOCATION}/${directory}" "${directory}" 2>/dev/null
-					current_parent="${directory}"
 				fi
 			done
-		fi
-	done
+			mkdir initramfs proc tmp sys 2>/dev/null
+			chmod 1777 tmp
 
-	mkdir initramfs proc tmp sys run 2>/dev/null
-	chmod 1777 tmp
+		fi
+	#XXX: end extremely confusing hunk
 
 	# have handy /mnt/cdrom (CDROOT_PATH) as well
 	_new_cdroot="${NEW_ROOT}${CDROOT_PATH}"
@@ -862,6 +921,12 @@ else
 		setup_unionfs /union_changes ${NEW_ROOT}
 		mkdir -p ${UNION}/tmp/.initrd
 	fi
+	if [ "${USE_AUFS_NORMAL}" -eq '1' ]
+	then
+		union_insert_dir ${UNION} ${NEW_ROOT}
+		mkdir -p ${UNION}/tmp/.initrd
+	fi
+
 fi
 
 # Mount the additional things as required by udev & systemd
@@ -905,6 +970,27 @@ then
 fi
 
 verbose_kmsg
+
+if [ "${USE_AUFS_NORMAL}" -eq '1' ]
+then
+	mkdir -p /${CHROOT}/.unions/memory 2>/dev/null
+	mount -o move /memory /${CHROOT}/.unions/memory || echo '*: Failed to move aufs /memory into the system root!'
+	for i in tmp var/tmp mnt/gentoo mnt/livecd
+	do
+		mkdir -p ${CHROOT}/$i
+		chmod 755 ${CHROOT}/$i
+	done
+	# This will prevent from putting junk on the CHANGESDEV
+	mkdir -p ${CHROOT}/usr/portage/distfiles
+	mount -t tmpfs tmpfs ${CHROOT}/var/tmp
+	mount -t tmpfs tmpfs ${CHROOT}/tmp
+	mount -t tmpfs tmpfs ${CHROOT}/usr/portage/distfiles
+	warn_msg "/tmp /var/tmp /usr/portage/distfiles are mounted in ram"
+	warn_msg "consider saving important files elsewhere..."
+	read -t 3 UNUSEDVAL
+	mount --bind ${NEW_ROOT}${CDROOT_PATH} ${CHROOT}${CDROOT_PATH}
+	mount --bind ${NEW_ROOT}/mnt/livecd ${CHROOT}/mnt/livecd
+fi
 
 good_msg "Booting (initramfs)"
 
